name: scrape-azpdl-sales

on:
  schedule:
    # 12:10 Asia/Shanghai == 04:10 UTC
    - cron: '10 4 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scripts/scrape_azpdl_sales.py

      - name: Commit and push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/** || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            REPORT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            git commit -m "chore(data): update AZPDL sales ${REPORT_DATE}"
            git push
          fi
